#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$DATABASE_ADMIN_USER" --dbname "$DATABASE_NAME" <<-EOSQL
  CREATE ROLE family_tree_user WITH LOGIN PASSWORD '$DATABASE_USER_PASSWORD';
  GRANT CONNECT ON DATABASE $DATABASE_NAME TO family_tree_user;
  GRANT USAGE ON SCHEMA public TO family_tree_user;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO family_tree_user;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO family_tree_user;
  ALTER DEFAULT PRIVILEGES FOR ROLE $DATABASE_ADMIN_USER IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO family_tree_user;
  ALTER DEFAULT PRIVILEGES FOR ROLE $DATABASE_ADMIN_USER IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO family_tree_user;
EOSQL
