#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_ADMIN_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE family_tree_user WITH LOGIN PASSWORD '$POSTGRES_PASSWORD';
  GRANT CONNECT ON DATABASE $POSTGRES_DB TO family_tree_user;
  GRANT USAGE ON SCHEMA public TO family_tree_user;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO family_tree_user;
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO family_tree_user;
  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_ADMIN_USER IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO family_tree_user;
  ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_ADMIN_USER IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO family_tree_user;
EOSQL
